//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServisOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cihaz
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cihaz()
        {
            this.Fatura = new HashSet<Fatura>();
        }
    
        public int Id { get; set; }
        public int MusteriId { get; set; }
        public string Takip_No { get; set; }
        public string Marka { get; set; }
        public string Ariza { get; set; }
        public string Barkod { get; set; }
        public string Seri_No { get; set; }
        public string Birim { get; set; }
        public string Personel { get; set; }
        public string Durum { get; set; }
        public string Musteri_Beyani { get; set; }
        public System.DateTime Giris_Tarihi { get; set; }
        public System.DateTime Cikis_Tarihi { get; set; }
        public string Uzerinde_Gelenler { get; set; }
    
        public virtual Musteri Musteri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fatura> Fatura { get; set; }
    }
}
