//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServisOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fatura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fatura()
        {
            this.FaturaStok = new HashSet<FaturaStok>();
        }
    
        public int Id { get; set; }
        public int MusteriId { get; set; }
        public int CihazId { get; set; }
        public Nullable<decimal> AltToplam { get; set; }
        public Nullable<decimal> KDV { get; set; }
        public Nullable<decimal> Toplam { get; set; }
        public Nullable<System.DateTime> FaturaTarihi { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual Cihaz Cihaz { get; set; }
        public virtual Musteri Musteri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FaturaStok> FaturaStok { get; set; }
    }
}
