//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServisOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class FaturaStok
    {
        public int Id { get; set; }
        public Nullable<int> FaturaId { get; set; }
        public int StokId { get; set; }
        public int StokAdedi { get; set; }
        public Nullable<decimal> AraToplam { get; set; }
    
        public virtual Fatura Fatura { get; set; }
        public virtual Stok Stok { get; set; }
    }
}
