//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServisOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personel
    {
        public int Personel_No { get; set; }
        public string Adi_Soyadi { get; set; }
        public string Birim { get; set; }
        public string Magaza { get; set; }
        public string Yetki { get; set; }
        public string Sifre { get; set; }
    }
}
