//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServisOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stok
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stok()
        {
            this.FaturaStok = new HashSet<FaturaStok>();
        }
    
        public int Id { get; set; }
        public int MagazaId { get; set; }
        public string Stok_Kodu { get; set; }
        public string Stok_Kategori { get; set; }
        public string Stok_Adi { get; set; }
        public decimal Stok_Birim_Fiyati { get; set; }
        public int Stok_Adeti { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FaturaStok> FaturaStok { get; set; }
        public virtual Magaza Magaza { get; set; }
    }
}
